openapi: 3.0.0
info:
  title: OpenAPI Node Project
  version: 1.0.0
  description: API documentation for OpenAPI Node.js project

servers:
  - url: http://localhost:3000/api/v1
    description: Version 1 API
  - url: http://localhost:3000/api/v2
    description: Version 2 API

paths:
  /:
    get:
      summary: Get all resources
      operationId: getAllResources
      responses:
        "200":
          description: Successfully retrieved resources
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Resource"

    post:
      summary: Create a new resource
      operationId: createResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Resource"
      responses:
        "201":
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "400":
          description: Bad request, invalid schema

  "/{id}":
    put:
      summary: Update an existing resource
      operationId: updateResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Resource"
      responses:
        "200":
          description: Successfully updated resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "404":
          description: Resource not found

    patch:
      summary: Modify an existing resource
      operationId: modifyResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Resource"
      responses:
        "200":
          description: Successfully modified resource
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "404":
          description: Resource not found

    delete:
      summary: Delete an existing resource
      operationId: deleteResource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully deleted resource
        "404":
          description: Resource not found

components:
  schemas:
    Resource:
      type: object
      required:
        - id
        - name
        - value
      properties:
        id:
          type: integer
          example: 0
        name:
          type: string
          example: "string"
        value:
          type: string
          example: "string"
